default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: combishackaton
  username: postgres
  password: postgres
  host: localhost
  port: 5432


test:
  <<: *default
  database: combishackaton
  username: postgres
  password: postgres
  host: localhost
  port: 5432

production:
  <<: *default
  database: combishackaton
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  #password: <%= ENV['COMBISHACKATONBACKEND_DATABASE_PASSWORD'] %>